#Basic Numpy

##Numpy stands for numerical python

####The starring role is played by the "ndarray"
####The numpy library also provides linear algebra routines
####Pandas is built on numpy
####There is overlap in what numpy provides, in terms of data analysis capabilities

In [2]:
#The standard way to import the numpy library
import numpy as np

#Constructing

In [125]:
#TODO create a python list to hold the following numbers 3, 4.7, 2, 0, 1.2, 1
#TODO convert the python list to an ndarry using the "np.array()" method
a_list = [3, 4.7, 2, 0, 1.2, 1]
a_np_array = np.array(a_list)
print a_np_array

[ 3.   4.7  2.   0.   1.2  1. ]


In [4]:
#TODO using the shape attribute print out the shape of the ndarray you created
#TODO using the dtype attribute print out the type of the ndarray you created
print a_np_array.shape
print a_np_array.dtype

(6,)
float64


In [5]:
#TODO create a second list of numbers 2, 3.4, 3.3, 6, 2, 1
#TODO in python create a new list which contains the 2 lists of numbers
#TODO convert this list of lists into a 2 dimensionl ndarray
#TODO confirm the dimensionality of the array using the ndim attribute, also print out the shape and type
b_list = [2, 3.4, 3.3, 6, 2, 1]
c_list = [a_list, b_list]
c_np_array = np.array(c_list)
print c_np_array.ndim
print c_np_array.shape
print c_np_array.dtype

2
(2, 6)
float64


####There are a number of helper functions to create arrays from scratch

In [6]:
#TODO using the np.zeros and np.ones methods create 4 ndarrays, 2 of type int, 2 of type float 
#hint: there is a dtype option within the array method that can be used to set the type
a1 = np.zeros(5, dtype=np.int)
a2 = np.zeros(5, dtype=np.float)
a3 = np.ones(5, dtype=np.int)
a4 = np.ones(5, dtype=np.float)

print a1, a2, a3, a4

[0 0 0 0 0] [ 0.  0.  0.  0.  0.] [1 1 1 1 1] [ 1.  1.  1.  1.  1.]


####It is often necessary to recast data types from one type to another, as we will see with the upcoming exploratory data analysis work

In [7]:
#TODO using the built in method astype convert one of the numerical arrays into an array of strings
#TODO confirm that the new array really is of dtype string
a1str = a1.astype(str)
print a1str
print type(a1str)
print a1str.dtype

['0' '0' '0' '0' '0']
<type 'numpy.ndarray'>
|S21


##Question: Does astype create a new copy of the array?

###Yes - even if the type of the new array is the same as that of the original array

####Often when you read datasets from file numbers get read as strings

In [8]:
#TODO convert the array of strings back to floats
a1float = a1str.astype(float)
print a1float

[ 0.  0.  0.  0.  0.]


In [9]:
#TODO what does the np.arange do
#TODO create an integer array containing 20 integers, starting at 50 and going up in steps of 2
int_array = np.arange(50, 90, 2)
print int_array
print len(int_array)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]
20


#Vectorization

In [10]:
#TODO create a 2 by 3 array of floats - use the array you created above or create new ones
float_array = np.ones((2,3), dtype=np.float)
print float_array
print float_array.shape

#OR

float_array_2 = np.array(([2, 4, 8], [2, 5, 6]))
print float_array_2
print float_array_2.shape

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
(2, 3)
[[2 4 8]
 [2 5 6]]
(2, 3)


In [11]:
#TODO produce an array of the squares of all the numbers
#TODO produce an array of the sum of all the numbers
#TODO produce an array where all the numbers are multiplied by 4.3
squares = float_array_2 * float_array_2
print squares
sums = float_array_2.sum()
print sums
four_pt_3 = float_array_2 * 4.3
four_pt_3

[[ 4 16 64]
 [ 4 25 36]]
27


array([[  8.6,  17.2,  34.4],
       [  8.6,  21.5,  25.8]])

##Question what is the difference between vectorization and broadcasting

#Quoting from Wes McKinney
###Using NumPy arrays enables you to express many kinds of data processing tasks as concise array expressions that might otherwise require *writing loops*. 

###This practice of replacing explicit loops with array expressions is commonly referred to as *vectorization*. 

###In general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their pure Python equivalents, with the biggest impact in any kind of numerical computations.

###Any arithmetic operations between equal-size arrays applies the operation elementwise

###Broadcasting describes how arithmetic works between arrays of different shapes. It is a very powerful feature, but one that can be easily misunderstood, even by experienced users. The simplest example of broadcasting occurs when combining a scalar value with an array.

####McKinney, Wes (2012-10-08). Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython (p. 97). O'Reilly Media. Kindle Edition. 

In [106]:
#Vectorization example:
test_array = np.array([[1, 2, 3], [1, 2, 3]])
print test_array * test_array

[[1 4 9]
 [1 4 9]]


In [126]:
#Broadcasting example (ultra simple example):
test_array * 3

array([[3, 6, 9],
       [3, 6, 9]])

#Basic Indexing, Slicing and Dicing

In [112]:
#TODO using the array of 20 integers you created above find:
#The 5th element
#The 5th to 8th elements inclusive
print int_array[4]
print int_array[4:8]

58
[58 60 62 64]


In [115]:
#TODO multiply the 5th to 8th elements by 5.6
#TODO now print the original array in full
int_array[4:8] *= 5.6
print int_array

[ 50  52  54  56 324 336 347 358  66  68  70  72  74  76  78  80  82  84
  86  88]


In [123]:
#A better example might be:
int_array_slice = int_array[4:8]
int_array_slice[0] = 1287876
print int_array

int_array_slice[:] = -10
print int_array

[     50      52      54      56 1287876     -10     -10     -10      66
      68      70      72      74      76      78      80      82      84
      86      88]
[ 50  52  54  56 -10 -10 -10 -10  66  68  70  72  74  76  78  80  82  84
  86  88]


##Question: What do you notice about the changes you made to the slice?

###The slice is a view to the original array. Both the original array and the slice point to the same thing. If you change the slice then the original array also changes. It's not a huge thing but on occasion it catches me out and I get unexpected results

In [118]:
#TODO This time make a slice by using the 'copy' method
#TODO Multiply this by 0.5
#TODO print the original array
int_array_slice = int_array[4:8].copy() * 0.5
print int_array
print int_array_slice

[ 50  52  54  56 324 336 347 358  66  68  70  72  74  76  78  80  82  84
  86  88]
[ 162.   168.   173.5  179. ]


####This is the difference between a view and a copy

In [130]:
#TODO using the array of 20 integers slice the array from the begining to the 10th element
#TODO now slice it from the 4th element to the end
#TODO assign 32 to all the elements of the slice
#TODO print the original array
print int_array[:10]
print int_array[3:]
int_array[3:] = 32
print int_array

[50 52 54 32 32 32 32 32 32 32]
[32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32]
[50 52 54 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32]


##Sorting

In [97]:
a = np.array([4, 5, 2, 8, 1])
#TODO using the built in sort method to sort this array
#TODO confirm the array has been sorted by printing out the array
a.sort()
print a

#This can be a little confusing as the sort occurs in place. a.sort() executes the in-place sort on a. It changes a.
#You can't do this "print a.sort()" - try it.
#You a.sort(), then you print a

[1 2 4 5 8]


In [101]:
a = np.array([[4, 3, 29], [8, 6, 11]])
#TODO print the shape of this multi-dimensional array
#TODO print the array and sort each row, reprint the array to confirm
print a.shape
a.sort(axis=1)
print a

a = np.array([[4, 3, 29], [8, 6, 11]])
#TODO now sort by columns
a.sort(axis=0)
print a

(2, 3)
[[ 3  4 29]
 [ 6  8 11]]
[[ 4  3 11]
 [ 8  6 29]]


##NP arrays as sets

In [90]:
names = np.array(['Jim', 'John', 'Bill', 'Tony', 'Jim', 'Bill', 'Daniel', 'Jim'])
#TODO print out just the unique names in this nd array
print np.unique(names)

#formal conversion to a set

names_set = set(names)
print names_set

['Bill' 'Daniel' 'Jim' 'John' 'Tony']
set(['Tony', 'Jim', 'John', 'Bill', 'Daniel'])


#Random Number Generation

Here is a linkg to the documentation for the random sampling routines built into numpy http://docs.scipy.org/doc/numpy/reference/routines.random.html#

These are incredibly useful and powerful

In [60]:
#TODO using np.random.rand create an array of 10 random numbers
rand_array = np.random.rand(10)
print rand_array

[ 0.39525025  0.62855481  0.19918225  0.30729624  0.02042127  0.31155328
  0.03596808  0.95924069  0.55319113  0.60677951]


#Universal Functions

####A function that performs elementwise operation on the data in an nddarray.

In [66]:
#TODO using the random number array you created above caluclate the following for all the elements of the array:
#the square root
#the absolute value
sqroot_array = np.sqrt(rand_array)
print sqroot_array
abs_array = np.abs(rand_array)
print abs_array
#Note there are 2 absolute value functions np.abs() and np.fabs()

[ 0.62868931  0.79281448  0.44629838  0.55434307  0.14290301  0.55816958
  0.18965252  0.97940834  0.74376819  0.77896053]
[ 0.39525025  0.62855481  0.19918225  0.30729624  0.02042127  0.31155328
  0.03596808  0.95924069  0.55319113  0.60677951]


In [82]:
#TODO create a boolean array by checking that each element of the array is "not a number"
bool_array = np.isnan(sqroot_array)
print bool_array

#conversely

test_array = np.array([[1, 2, 3, 5], [np.NaN, np.NaN]])
bool_array2 = np.isnan(test_array[1])
print bool_array2

[False False False False False False False False False False]
[ True  True]


##Mathematical and Statistical Methods

In [16]:
#TODO create an array of 1000 normally distributed numbers (standard normal distribution)
rn_array = np.random.normal(0, 1, 1000)
print len(rn_array)
#print rn_array

1000


In [29]:
#TODO get the mean, sum, standard deviation, and cumulative sum
rn_array_mean = rn_array.mean()
print rn_array_mean
rn_array_std = rn_array.std()
print rn_array_std
rn_array_cumsum = rn_array.cumsum()
print "original array"
for i in xrange(10):
    print "{:5.2f}".format(rn_array[i]), 
print "\ncumulative sum of original array"
for i in xrange(10):
    print "{:5.2f}".format(rn_array_cumsum[i]), 

0.0320237964792
0.998142664358
original array
-0.39 -0.70  0.37  1.57  2.08 -0.15 -2.13 -0.06 -0.05 -1.11 
cumulative sum of original array
-0.39 -1.09 -0.72  0.85  2.93  2.78  0.65  0.59  0.54 -0.57


In [53]:
##Question: To calculate standard deviation does np.std() use 1/N or 1/(N-1)
#test_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
test_array = np.array(np.arange(1000)) 
N = len(test_array)
test_array_mean = test_array.mean()
sum_sq_array = (test_array - test_array_mean) * (test_array - test_array_mean)
sum_sq = sum_sq_array.sum()
man_mean_a = np.sqrt(1.0/N * sum_sq)
man_mean_b = np.sqrt(1.0/(N-1) * sum_sq)

print "Manuually evaluated using 1/N:", man_mean_a
print "Manuually evaluated using 1/N-1:", man_mean_b
print "Built in function:", test_array.std()

if man_mean_a - test_array.std() < 1e-16:
    print "np standard deviation uses 1/N"
else:
    print "np standard deviation uses 1/N-1"

499.5
Manuually evaluated using 1/N: 288.674990257
Manuually evaluated using 1/N-1: 288.819436096
Built in function: 288.674990257
np standard deviation uses 1/N


In [59]:
#TODO write no more than 4 lines of code to justify your answer
test_array = np.array(np.arange(1000)) 
man_mean_a = np.sqrt(1.0/len(test_array) * ((test_array - test_array_mean) * (test_array - test_array_mean)).sum())
man_mean_b = np.sqrt(1.0/(len(test_array)-1) * ((test_array - test_array_mean) * (test_array - test_array_mean)).sum())
print man_mean_a, man_mean_b, test_array.std()

288.674990257 288.819436096 288.674990257


##Meshgrid

In [78]:
points = np.arange(-1, 2, 1)
print "points is an array of  ", len(points), "points:", points

#To create a meshgrid we would therefore need a total of 9 points in a grid, 3 along an x axis and 3 along a y axis
x, y = np.meshgrid(points, points)

print "the x axis points are\n", x
print "the y axis points are\n", y

print "The individual pairs of points could be generated like this:"

for i in np.arange(len(points)):
    for j in np.arange(len(points)):
        print "(", x[i][j], ",", y[i][j], ")",

points is an array of   3 points: [-1  0  1]
the x axis points are
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
the y axis points are
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]
The individual pairs of points could be generated like this:
( -1 , -1 ) ( 0 , -1 ) ( 1 , -1 ) ( -1 , 0 ) ( 0 , 0 ) ( 1 , 0 ) ( -1 , 1 ) ( 0 , 1 ) ( 1 , 1 )


####Meshgrad is useful for 3d plotting