- Discrete variables can often take on more than 2 values, taking on one of K possible, mutually exclusive, values

- Represent this using the 1-of-K scheme: a variable is a K dimensional vector where 1 of the elements has value 1, and all others have value 0

- Example:

$K=6$

$x3 = 1$

$x = (0,0,1,0,0,0)$

$\sum_{k=1}^{K} x_k=1$

$\text{Let }p(x_k=1) = \mu_k$

$\text{then the distribution of x is given by }p(x\text{ }|\text{ }\overline{\mu})=\prod_{k=1}^{K} \mu_k^{x_k}$

$\text{where }\overline{\mu}=(u_1, u_2, u_3, ... , u_k)$

$\text{and the parameters } \mu_k \geq 0 \text{ and }\sum_{k=1}^{K}\mu_k=1 \text{ because they represent probabilities}$

$E[x\text{ }|\text{ }\mu]=\mu$

- The distribution is a generalization of the Bernoulli distribution to two or more outcomes.

$p = \frac{n}{n_{1}!n_{2}!n_{3}!}p^{n_{1}}_{1}p^{n_{2}}_{2}p^{n_{3}}_{3}$

multinomial 3 outcomes

where

- p is the probability,

- n is the total number of events

- n1 is the number of times Outcome 1 occurs,

- n2 is the number of times Outcome 2 occurs,

- n3 is the number of times Outcome 3 occurs,

- p1 is the probability of Outcome 1

- p2 is the probability of Outcome 2, and

- p3 is the probability of Outcome 3.

In [17]:
from IPython.display import Latex
from IPython.display import Math

#scipy does not have the multinomial - it is part of numpy
import numpy as np

In [34]:
k = 6
#np.random.multinomial(number of experiemnts, probabilities, number of results to return)

print "size = 1"
mrvars = np.random.multinomial(1, [1/6.]*6, size=1)
print mrvars
print "\n"

print "size = 2"
mrvars = np.random.multinomial(1, [1/6.]*6, size=2)
print mrvars
print "\n"

n = 20
s = 1
print "{:d} experiments, size = {:d}".format(n, s)
mrvars = np.random.multinomial(1, [1/6.]*6, size=s)
print mrvars
print "\n"

n = 20
s = 2
print "{:d} experiments, size = {:d}".format(n, s)
mrvars = np.random.multinomial(1, [1/6.]*6, size=s)
print mrvars
print "\n"

print "Checking that each row sums to 1"
for i in xrange(s):
    print "row {:d} = {:5.2f}".format(i, mrvars[i].sum())
print "\n"
    
    
print "The vector of mu's"
u = np.zeros(k)
for i in xrange(s):
    for j in xrange(k):
        u[j] += mrvars[i][j]
        
for j in xrange(k):
    u[j] /= s

print u
print "\n"

print "What is the probability of \n", x, "?"

x = np.array([0, 1, 0, 0, 0, 0])
px = 1.0
for j in xrange(k):
    px = px * np.power(u[j], x[j])
    
print "Answer = {:5.2f}".format(px)

size = 1
[[1 0 0 0 0 0]]


size = 2
[[0 1 0 0 0 0]
 [1 0 0 0 0 0]]


20 experiments, size = 1
[[1 0 0 0 0 0]]


20 experiments, size = 2
[[0 0 0 0 0 1]
 [0 1 0 0 0 0]]


Checking that each row sums to 1
row 0 =  1.00
row 1 =  1.00


The vector of mu's
[ 0.   0.5  0.   0.   0.   0.5]


What is the probability of 
[0 1 0 0 0 0] ?
Answer =  0.50
