In [2]:
from IPython.display import Latex
from IPython.display import Math

#scipy does not have the multinomial - it is part of numpy
import numpy as np

---
Multinomial Distribution
=====
***

####A discrete distribution that can be considered a generalization of the Bernoulli Distribution

#####The discrete random variable takes on more than one of two values

#####The discrete random variable can take on one out of K possible, mutually exclusive, values

#####This is represented as a 1-out-of-K coding scheme, producing a K-dimensional vector where only one of the elements has the value of 1

#####All other members of the vector have the value of 0

- The binomial distribution allows one to compute the probability of obtaining a given number of binary outcomes. For example, it can be used to compute the probability of getting 6 heads out of 10 coin flips. The flip of a coin is a binary outcome because it has only two possible outcomes: heads and tails.

- The multinomial distribution can be used to compute the probabilities in situations in which there are more than two possible outcomes.

####Example:

$\text{Suppose }K=6 \text{ and }x3 = 1$

$\vec{x} = (0,0,1,0,0,0)$

#####and

$\sum_{k=1}^{K} x_k=1$


#####Each of the dimensions has an associated probability

$\text{In each dimension the probability that }x_{k}=1\text{ is given by the parameter }\mu_{k}$


$p(x_k=1) = \mu_k$

$p(x_k=0) = 1.0 - \mu_k$


$p(x\text{ }|\text{ }\vec{\mu})=\prod_{k=1}^{K} \mu_k^{x_k}$

$\text{where }\overline{\mu}=(u_1, u_2, u_3, ... , u_k)$

$\text{and the parameters } \mu_{k} \geq 0 \text{ and }\mu_{k} \leq 1 \text{ and }\sum_{k=1}^{K}\mu_k=1$


###The distribution is a generalization of the Bernoulli distribution to two or more outcomes.

- for example a multinomial with 3 outcomes

$p = \frac{n}{n_{1}!n_{2}!n_{3}!}p^{n_{1}}_{1}p^{n_{2}}_{2}p^{n_{3}}_{3}$

where

- p is the probability,

- n is the total number of events

- n1 is the number of times Outcome 1 occurs,

- n2 is the number of times Outcome 2 occurs,

- n3 is the number of times Outcome 3 occurs,

- p1 is the probability of Outcome 1

- p2 is the probability of Outcome 2, and

- p3 is the probability of Outcome 3.

- NB: he binomial distribution is a special case of the multinomial when k = 2.

####Example

- For example, suppose that two chess players had played numerous games and it was determined that the probability that Player A would win is 0.40, the probability that Player B would win is 0.35, and the probability that the game would end in a draw is 0.25. 

- The multinomial distribution can be used to answer questions such as: "If these two chess players played 12 games, what is the probability that Player A would win 7 games, Player B would win 2 games, and the remaining 3 games would be drawn?"

- Let's use the above formula:

#####n = 12 (12 games are played),
#####n1 = 7 (number won by Player A),
#####n2 = 2 (number won by Player B),
#####n3 = 3 (the number drawn),
#####p1 = 0.40 (probability Player A wins)
#####p2 = 0.35(probability Player B wins)
#####p3 = 0.25(probability of a draw)

In [11]:
n = 12
n1 = 7
n2 = 2
n3 = 3
p1 = 0.40
p2 = 0.35
p3 = 0.25
prb = (np.math.factorial(n)/(np.math.factorial(n1)*np.math.factorial(n2)*np.math.factorial(n3)))*np.power(p1, n1)*\
np.power(p2, n2)* np.power(p3, n3)
print "The probability of Player A winning 7 games, Player B winning 2 games, with 3 draws is {:5.4f}".format(prb)

The probability of Player A winning 7 games, Player B winning 2 games, with 3 draws is 0.0248


In [30]:
k = 6
#np.random.multinomial(number of experiemnts, probabilities, number of results to return)

print "size = 1"
mrvarsA = np.random.multinomial(1, [1/6.]*6, size=1)
print mrvarsA
print "\n"

print "size = 2"
mrvarsB = np.random.multinomial(1, [1/6.]*6, size=2)
print mrvarsB
print "\n"

nC = 1
sC = 200000
print "{:d} experiment, size = {:d}".format(nC, sC)
mrvarsC = np.random.multinomial(nC, [1/6.]*6, size=sC)
print mrvarsC
print "\n"

n = 20
s = 2
print "{:d} experiments, size = {:d}".format(n, s)
mrvarsD = np.random.multinomial(n, [1/6.]*6, size=s)
print mrvarsD
print "\n"



print "Checking that each row sums to 1 (when you have a single trial)"
for i in xrange(s):
    print "row {:d} = {:5.2f}".format(i, mrvarsB[i].sum())
print "\n"
    
    
print "The vector of mu's"
u = np.zeros(k)
for i in xrange(sC):
    for j in xrange(k):
        u[j] += mrvarsC[i][j]
        
for j in xrange(k):
    u[j] /= sC

print u
print "\n"

x = np.array([0, 1, 0, 0, 0, 0])
print "What is the probability of \n", x, "?"

px = 1.0
for j in xrange(k):
    px = px * np.power(u[j], x[j])
    
print "Answer = {:5.2f}".format(px)

size = 1
[[0 0 0 1 0 0]]


size = 2
[[0 0 0 0 1 0]
 [0 1 0 0 0 0]]


1 experiment, size = 200000
[[0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 ..., 
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]]


20 experiments, size = 2
[[5 4 3 2 2 4]
 [5 2 5 5 3 0]]


Checking that each row sums to 1 (when you have a single trial)
row 0 =  1.00
row 1 =  1.00


The vector of mu's
[ 0.167055  0.16669   0.16697   0.165865  0.16616   0.16726 ]


What is the probability of 
[0 1 0 0 0 0] ?
Answer =  0.17
